import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import styles from '../styles/Home.module.css'
import { PrefecturesResponse } from '@/pages/api/prefectures'

async function fetcher(key: string) {
  return fetch(key)
    .then((res) => res.json())
    .then((data) => data.result as Promise<PrefecturesResponse[] | null>)
}

const Home: NextPage = () => {
  const { data, error } = useSWR('/api/prefectures', fetcher)
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <fieldset>
          <legend>test</legend>
          {data.map((prefectures) => (
            <div key={prefectures.prefCode}>
              <input type='checkbox' id={prefectures.prefName} name={prefectures.prefName} />
              <label htmlFor={prefectures.prefName}>{prefectures.prefName}</label>
            </div>
          ))}
        </fieldset>
      </main>
    </div>
  )
}

export default Home
